<?php

namespace App\Http\Middleware;

use App\Services\SettingsService;
use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

/**
 * Require the bearer token the settings file holds.
 *
 * Loopback is not a boundary between accounts or between processes: every program the user runs
 * can reach the port, and the tools behind it reach arbitrary shell. The token is generated by
 * McpService when the server first starts and handed to the client through the `claude mcp add`
 * command on the Settings screen.
 *
 * A blank stored token denies everything rather than allowing everything, so a hand-edited or
 * truncated settings file fails closed.
 *
 * 401 rather than 403, so the package's AddWwwAuthenticateHeader middleware can describe the
 * challenge and clients report it as authentication rather than as a missing server.
 */
class EnsureMcpTokenIsValid
{
    /**
     * Handle an incoming request.
     *
     * @param  Closure(Request): Response  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        try {
            $token = app(SettingsService::class)->loadSettings()->mcp_token;
        } catch (Throwable) {
            abort(401, 'The MCP server could not read its own settings.');
        }

        $presented = $request->bearerToken();

        if (blank($token) || blank($presented) || ! hash_equals($token, $presented)) {
            abort(401, 'A valid bearer token is required.');
        }

        return $next($request);
    }
}
